# Generated by Django 3.2.7 on 2021-11-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_alter_cargo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargo',
            table='chevyparts.empleados_cargo',
        ),
    ]
