# Generated by Django 3.2.7 on 2021-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Razon_Social', models.CharField(max_length=100)),
                ('Ruc', models.IntegerField(max_length=13)),
                ('Teléfono', models.IntegerField(max_length=10)),
            ],
        ),
    ]
